name: "Test using cargo test"

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: "Test using cargo test"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.1.7
      
      - name: "Setup the Rust stable toolchain"
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: "stable"
          override: true

      - name: "Cache target directory"
        uses: actions/cache@v4.0.2
        with:
          key: "target"
          path: |
            target

      - name: "Run cargo test"
        uses: actions-rs/cargo@v1.0.1
        with:
          command: "test"
